image: 
  name: "hashicorp/terraform:0.12.24"
  entrypoint: [""]

stages:
  - preFlight
  - step1
  - step2
  - step3

build:
  stage: preFlight
  script:
    - pwd
    - cd terraform/aleksey
    - ls -al
    - terraform -version

test:
  stage: step1
  script:
    - pwd
    - cd terraform/aleksey
    - ls -al
    - terraform init
    - terraform validate

plan:
  stage: step2
  script:
    - cd terraform/aleksey
    - terraform init
    - terraform plan -var "lock=true"

apply:
  stage: step3
  when: manual
  script:
    - cd terraform/aleksey
    - terraform init
    - terraform apply -var "lock=true" -auto-approve
