image: docker

services:
  - docker:dind

stages:
  - test
  - deploy

test:
  stage: test
  script:
    echo run tests here

deploy:
  stage: deploy
  script:
  - docker info
  - apk update
  - apk upgrade
  - apk add python python-dev py-pip build-base
  - pip install docker-compose
  - docker-compose up -d build

