image: 
  name: "hashicorp/terraform:0.12.24"
  entrypoint: [""]

stages:
  - preFlight
  - step1
  - step2
  - step3

variables:
  PLAN: plan-$CI_JOB_ID.tfplan

build:
  stage: preFlight
  script:
    - env
    - cd terraform/aleksey
    - terraform -version
  
test:
  stage: step1
  script:
    - cd terraform/aleksey
    - terraform init
    - terraform validate

plan:
  stage: step2
  script:
    - cd terraform/aleksey
    - terraform init
    - terraform plan -var "lock=true" -out $PLAN
    - ls -la
  artifacts:
    name: plan
    paths:
      - $PLAN


apply:
  stage: step3
  when: manual
  script:
    - cd terraform/aleksey
    - terraform init
    - terraform apply $PLAN -var "lock=true" -auto-approve
  artifacts:
    name: plan
    paths:
      - $PLAN
