image: docker

variables:
  DOCKER_HOST: tcp://ec2-54-81-190-182.compute-1.amazonaws.com:2375


services:
  - docker:dind

stages:
  - deploy

deploy:
  stage: deploy
  script:
  - docker info
  - apk update
  - apk upgrade
  - apk add --update-cache python python-dev py-pip build-base 
  - pip install docker-compose
  - docker-compose up -d build

