image: tmaier/docker-compose:latest

variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

before_script:
- docker info

build:
  stage: build
  script:
  - docker-compose -f docker-compose.test.yml build
