image: docker

services:
  - docker:dind

stages:
  - deploy

deploy:
  stage: deploy
  script:
  - docker info
  - apk update
  - apk upgrade
  - apk add python
  - pip install docker-compose
  - docker-compose up -d build

