image: "python:3.7"

stages:
  - preFlight
  - step1
  - step2
  - step3

build:
  stage: preFlight
  script:
    - pwd
    - cd terraform/aleksey
    - curl -o terraform.zip https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_386.zip
    - unzip terraform.zip

test:
  stage: step1
  script:
    - pwd
    - cd terraform/aleksey
    - ./terraform validate

plan:
  stage: step2
  script:
    - cd terraform/aleksey
    - ./terraform plan

apply:
  stage: step3
  script:
    - cd terraform/aleksey
    - ./terraform apply
