image: tmaier/docker-compose:latest
variables:
  DOCKER_DRIVER: overlay
services:
- docker:dind

before_script:
  - docker info
  - apk add --no-cache python python-dev py-pip libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose
  - docker-compose --version
 
build:
  stage: build
  script:
  - docker-compose -d build
